services:

  Rollbar\Symfony\RollbarBundle\Factories\RollbarHandlerFactory:
    arguments:
      - '@service_container'

  Monolog\Handler\RollbarHandler:
    factory: ['@Rollbar\Symfony\RollbarBundle\Factories\RollbarHandlerFactory', createRollbarHandler]
    tags:
      - { name: monolog.logger, channel: rollbar }

  Rollbar\Monolog\Handler\RollbarHandler:
    alias: Monolog\Handler\RollbarHandler

  Rollbar\Symfony\RollbarBundle\Payload\Generator:
    arguments:
      - '@service_container'
